module.exports = [
  {
    name: 'default',
    type: 'postgres',
    url: '',
    host: 'localhost',
    port: 5433,
    username: 'postgres',
    password: 'root',
    database: 'onion_dev',
    logging: true,
    migrationsRun: true,
    entities: [`${__dirname}/src/infrastructure/database/entities/**/*.ts`],
    migrations: [`${__dirname}/src/infrastructure/database/migrations/**/*.ts`],
    subscribers: [
      `${__dirname}/src/infrastructure/database/subscribers/**/*.ts`,
    ],
    seeds: ['src/infrastructure/database/fixtures/seeds/*.ts'],
    factories: ['src/infrastructure/database/fixtures/factories/*.ts'],
    cli: {
      entitiesDir: 'src/infrastructure/database/entities',
      migrationsDir: 'src/infrastructure/database/migrations',
      subscribersDir: 'src/infrastructure/database/subscribers',
    },
  },
  {
    name: 'onion_test',
    type: 'postgres',
    host: 'localhost',
    port: 5433,
    username: 'postgres',
    password: 'root',
    database: 'onion_test',
    logging: false,
    entities: [`${__dirname}/src/infrastructure/database/entities/**/*.ts`],
    migrations: [`${__dirname}/src/infrastructure/database/migrations/**/*.ts`],
  },
];
