module.exports = [
  {
    name: 'default',
    type: 'postgres',
    url: '',
    host: 'localhost',
    port: 5433,
    username: 'postgres',
    password: 'root',
    database: 'onion_dev',
    logging: true,
    migrationsRun: true,
    entities: [`${__dirname}/src/infrastructure/db/entities/**/*.ts`],
    migrations: [`${__dirname}/src/infrastructure/db/migrations/**/*.ts`],
    subscribers: [`${__dirname}/src/infrastructure/db/subscribers/**/*.ts`],
    seeds: ['src/infrastructure/db/fixtures/seeds/*.ts'],
    factories: ['src/infrastructure/db/fixtures/factories/*.ts'],
    cli: {
      entitiesDir: 'src/infrastructure/db/entities',
      migrationsDir: 'src/infrastructure/db/migrations',
      subscribersDir: 'src/infrastructure/db/subscribers',
    },
  },
  {
    name: 'onion_test',
    type: 'postgres',
    host: 'localhost',
    port: 5433,
    username: 'postgres',
    password: 'root',
    database: 'onion_test',
    logging: false,
    entities: [`${__dirname}/src/infrastructure/db/entities/**/*.ts`],
    migrations: [`${__dirname}/src/infrastructure/db/migrations/**/*.ts`],
    subscribers: [`${__dirname}/src/infrastructure/db/subscribers/**/*.ts`],
    seeds: ['test/config/seeds/*.ts'],
    factories: [`${__dirname}/src/infrastructure/db/fixtures/factories/*.ts`],
  },
];
